version: '3'
 
services:
 
  web:
    build: ./docker-file/web/
    ports:
      - 8080:80
    volumes:
      - ./volumes/web/html:/var/www/html
    depends_on:
      - db
 
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: sample_db
      POSTGRES_USER: sample_user
      POSTGRES_PASSWORD: sample_test
      TZ: 'Asia/Tokyo'
    ports:
      - 5433:5432
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
