version: '3'

services:

  web:
    build: ./docker-file/web/
    ports:
      - 8080:80
    volumes:
      - ./volumes/web/html/sample:/home
    working_dir: /home
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5433:5432
    volumes:
      - ./docker-file/db/init:/docker-entrypoint-initdb.d
